version: '2.4'
#networks:
#  default:
#    external:
#      name: "host"
services:
  jobmanager:
    image: 172.17.161.80:5000/myflink:1.8.2
    container_name: flink_jobmanager
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TZ=Asia/Shanghai
    volumes:
      - ./logs/flink:/opt/flink/log
    privileged: true
    ulimits:
      core: 0

  taskmanager:
    image: 172.17.161.80:5000/myflink:1.8.2
    container_name: flink_taskmanager
    expose:
      - "6121"
      - "6122"
    ports:
      - 10514:10514/udp
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    volumes:
      - ./logs/flink:/opt/flink/log
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TZ=Asia/Shanghai
      - TASK_RUNTIME_MEMORY=4096m
      - NUMBER_TASK_SLOTS=8
    ulimits:
      core: 0

